name: qr-cli
base: core24
version: '0.1'
summary: A simple QR code reader and generator
description: |
  A simple QR code reader. Uses OpenCV-Python to load an image file and detect, decode QR codes

  ```bash
  usage: qr-cli [-h] [-v] [-o OUTPUT] [--many-ok] image_path

  Read QR codes from an image file.

  positional arguments:
    image_path            Path to the image file containing the QR code.

  options:
    -h, --help            show this help message and exit
    -v, --verbose         Enable verbose output.
    -o OUTPUT, --output OUTPUT
                          Path to save the decoded QR code output.
    --many-ok             Allow multiple QR codes in the image.
  ```

license: MIT
grade: stable
confinement: strict

lint:
  ignore:
    - library
parts:
  qr-cli:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    override-build: |
      craftctl default
      # copy main.py to bin/qr-cli
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp $CRAFT_PART_SRC/src/qr_reader_cli/main.py $CRAFT_PART_INSTALL/bin/qr-cli
      # make it executable
      chmod +x $CRAFT_PART_INSTALL/bin/qr-cli

    build-packages:
      - build-essential
    stage-packages:
      - libgl1
    python-packages:
      - opencv-python-headless



apps:
  qr-cli:
    command: bin/qr-cli
    plugs:
      - home
