name: qr-cli
base: core24
version: '0.1'
title: QR Reader CLI
summary: A simple QR code reader and generator
description: |
  A simple QR code reader. Uses OpenCV-Python to load an image file and detect, decode QR codes

  Read QR code interactively from webcam
  `qr-cli`

  Read QR code interactively from webcam without live display
  `qr-cli --no-display`

  Image with single QR code
  `qr-cli -i ./path/to/file.jpg`

  Image with multiple QR codes
  `qr-cli -i ./path/to/file.jpg --many-ok`

  Output result to file
  `qr-cli -i ./path/to/file.jpg -o result.json`

license: MIT
grade: stable
confinement: strict
source-code: https://github.com/alexdlukens/qr-reader-cli
issues: https://github.com/alexdlukens/qr-reader-cli/issues
contact: 
  - alexdlukens@gmail.com
website: 
  - https://alukens.com
lint:
  ignore:
    - library
parts:
  poetry-deps:
    plugin: nil
    override-build: |
      craftctl default
      curl -sSL https://install.python-poetry.org | python3 -
      pip install "poetry-plugin-export>=1.8" --break-system-packages
  qr-cli:
    plugin: poetry
    after: [poetry-deps]
    source: .
    stage-packages:
      - libgl1



apps:
  qr-cli:
    command: bin/qr-cli
    plugs:
      - home
      - camera
