name: qr-cli
base: core24
version: '0.1'
summary: A simple QR code reader and generator
description: |
  A simple QR code reader. Uses OpenCV-Python to load an image file and detect, decode QR codes

  Image with single QR code
  `qr-cli ./path/to/file.jpg`

  Image with multiple QR codes
  `qr-cli ./path/to/file.jpg --many-ok`

  Output result to file
  `qr-cli ./path/to/file.jpg -o result.json`

license: MIT
grade: stable
confinement: strict

lint:
  ignore:
    - library
parts:
  qr-cli:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    override-build: |
      craftctl default
      # copy main.py to bin/qr-cli
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp $CRAFT_PART_SRC/src/qr_reader_cli/main.py $CRAFT_PART_INSTALL/bin/qr-cli
      # make it executable
      chmod +x $CRAFT_PART_INSTALL/bin/qr-cli

    build-packages:
      - build-essential
    stage-packages:
      - libgl1
    python-packages:
      - opencv-python-headless



apps:
  qr-cli:
    command: bin/qr-cli
    plugs:
      - home
      - camera
