name: qr-cli
base: core24
version: '0.1'
summary: A simple QR code reader and generator
description: |
  A simple QR code reader and generator

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  qr-cli:
    # See 'snapcraft plugins'
    plugin: poetry
    source: .
    override-build: |
      craftctl default
      # copy main.py to bin/qr-cli
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp $CRAFT_PART_SRC/qr_reader_cli/main.py $CRAFT_PART_INSTALL/bin/qr-cli
      # make it executable
      chmod +x $CRAFT_PART_INSTALL/bin/qr-cli

apps:
  qr-cli:
    command: bin/qr-cli
    plugs:
      - home
